default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: 'localhost'
development:
  <<: *default
  database: 'samkimmbp'
test:
  <<: *default
  database: 'samkimmbp'
production:
  <<: *default
  database: 'samkimmbp'